baseURL: 'https://ark31.info'
languageCode: 'en-us'
title: "Diary Of  Mad Engineer"
theme: "PaperMod"



params:
  assets:
    favicon: "/assets/favicon.ico"
    favicon16x16: "/assets/favicon-16x16.png"
    favicon32x32: "/assets/favicon-32x32.png"
    apple_touch_icon: "/assets/apple-touch-icon.png"
    

  profileMode:
    enabled: true
    title: "Brandon Blog" # optional default will be site title
    subtitle: "Working Blog site built with Hugo"
    imageUrl: "/images/bleach-styled-image.png" # optional
    imageTitle: "Profile Pic" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size
    buttons:
      - name: Archive
        url: "archives"
      - name: Resume
        url: "resume"
      - name: Blog
        url: "/posts"


  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/pattersonbl2"
    - name: "Linkedln"
      url: "https://www.linkedin.com/in/pattersonbl2/"
  label:
    text: "Home"
    icon: "/assets/apple-touch-icon.png"
    iconHeight: 35

outputs:
  home:
    - HTML
    - RSS
    - JSON 