baseURL: 'https://ark31.info'
languageCode: 'en-us'
title: "Diary Of  Mad Engineer"
theme: "PaperMod"

params:
  profileMode:
    enabled: true
    title: "Brandon Blog" # optional default will be site title
    subtitle: "Working Blog site built with Hugo"
    imageUrl: "/images/bleach-styled-image.png" # optional
    imageTitle: "Profile Pic" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size
    buttons:
      - name: Archive
        url: "archives"
      - name: Resume
        url: "resume"
      - name: Blog
        url: "/Posts"


  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/pattersonbl2"
    - name: "Linkedln"
      url: "https://www.linkedin.com/in/pattersonbl2/"

outputs:
  home:
    - HTML
    - RSS
    - JSON 