baseURL: 'https://ark31.info'
languageCode: 'en-us'
title: "Thought of  Mad Sre"
theme: "PaperMod"

params:
  profileMode:
    enabled: true
    title: "Brandon Blog" # optional default will be site title
    subtitle: "Website Deploy with hugo"
    imageUrl: "<image link>" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Archive
        url: "/archive"
      - name: Resume
        url: "/resume"
      - name: Github
        url: "https://github.com/pattersonbl2"

  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/pattersonbl2"
    - name: "Linkedln"
      url: "https://www.linkedin.com/in/pattersonbl2/"